# Generated by Django 4.1.3 on 2022-11-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0002_message_recipient_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_location',
            new_name='location',
        ),
    ]
