# Generated by Django 4.1.3 on 2022-11-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0003_rename_message_location_message_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('contact_email', models.CharField(max_length=256, null=True)),
                ('contact_phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=256)),
                ('cause_of_injury', models.TextField(help_text='What was the cause of the injury?', null=True)),
                ('nature_of_injury', models.TextField(help_text='What is the nature of the injury?', null=True)),
                ('effects_of_injury', models.TextField(help_text='What are the signs/symptoms of the injury, other observations?', null=True)),
                ('Treatment_Provided', models.TextField(help_text='What treatment has been provided to the injury at this', null=True)),
                ('emergency_message_type', models.CharField(choices=[('S', 'Security'), ('M', 'Medical'), ('E', 'Environmental')], default='M', max_length=1, null=True)),
                ('Has_this_been_escalated', models.BooleanField(default=False)),
                ('escalated_to', models.CharField(max_length=160)),
                ('emergency_action', models.TextField()),
                ('Has_this_been_resolved', models.BooleanField(default=False)),
                ('patient_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_patient_ref', to='float.emergencypatient')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_emergency_recipient', to='float.operator')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_emergency_sender', to='float.operator')),
            ],
        ),
    ]
