# Generated by Django 4.1.3 on 2022-11-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0004_emergencypatient_emergencymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymessage',
            name='patient_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_patient_ref', to='float.emergencypatient'),
        ),
    ]
