# Generated by Django 4.1.3 on 2022-12-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0006_alter_emergencymessage_escalated_to_historicalrole_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencymessage',
            old_name='Treatment_Provided',
            new_name='treatment_provided',
        ),
        migrations.RenameField(
            model_name='historicalemergencymessage',
            old_name='Treatment_Provided',
            new_name='treatment_provided',
        ),
        migrations.RemoveField(
            model_name='emergencymessage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emergencypatient',
            name='patient_ref',
        ),
        migrations.RemoveField(
            model_name='historicalemergencymessage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalemergencypatient',
            name='patient_ref',
        ),
        migrations.RemoveField(
            model_name='historicalmessage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicaloperator',
            name='order',
        ),
        migrations.RemoveField(
            model_name='message',
            name='location',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='order',
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='Has_this_been_controlled',
            field=models.BooleanField(default=False, help_text='Select if this incident has been controlled but has yet to be resolved.'),
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='event_occurance_timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Time of the emergency events occuring', null=True),
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='message_entry_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='emergencymessage',
            name='reported_location',
            field=models.CharField(blank=True, help_text='What is the reported location of the incident?', max_length=256),
        ),
        migrations.AddField(
            model_name='emergencypatient',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalemergencymessage',
            name='Has_this_been_controlled',
            field=models.BooleanField(default=False, help_text='Select if this incident has been controlled but has yet to be resolved.'),
        ),
        migrations.AddField(
            model_name='historicalemergencymessage',
            name='event_occurance_timestamp',
            field=models.DateTimeField(blank=True, editable=False, help_text='Time of the emergency events occuring', null=True),
        ),
        migrations.AddField(
            model_name='historicalemergencymessage',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalemergencymessage',
            name='message_entry_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalemergencymessage',
            name='reported_location',
            field=models.CharField(blank=True, help_text='What is the reported location of the incident?', max_length=256),
        ),
        migrations.AddField(
            model_name='historicalemergencypatient',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='message_entry_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='reported_location',
            field=models.CharField(blank=True, help_text="Sender Operator's reported location, if provided - recipient location should be recorded if needed as message info.", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='command_weighting',
            field=models.PositiveIntegerField(help_text='Provide the order in which you wish to have this operator appear in the Message dropdown.', null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalplace',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='last_updated_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_entry_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reported_location',
            field=models.CharField(blank=True, help_text="Sender Operator's reported location, if provided - recipient location should be recorded if needed as message info.", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='command_weighting',
            field=models.PositiveIntegerField(help_text='Provide the order in which you wish to have this operator appear in the Message dropdown.', null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='last_updated_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='Has_this_been_escalated',
            field=models.BooleanField(default=False, help_text='Select if this incident has been delegated to another authority, as specificed below:'),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='Has_this_been_resolved',
            field=models.BooleanField(default=False, help_text='Select if this incident has been resolved and no further action is required.'),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='emergency_action',
            field=models.TextField(help_text='Briefly explain what has been done to address the emergency situation. Provide as much detail as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='emergency_message_type',
            field=models.CharField(choices=[('C', 'Child Safety'), ('E', 'Environmental'), ('M', 'Medical'), ('O', 'Other'), ('S', 'Security')], default='M', help_text='Select the nature of the emergency incident.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='escalated_to',
            field=models.CharField(help_text='Specify a 000 department, company, custodian, etc.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='patient_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_patient_ref', to='float.emergencypatient'),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Message was received by this Operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_emergency_recipient', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='emergencymessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message was sent by this Operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_emergency_sender', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='age',
            field=models.IntegerField(blank=True, help_text='Approximate age of patient, if known.', null=True),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='contact_email',
            field=models.CharField(blank=True, help_text='Obtain if required for follow up after incident has been controlled.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone is preferred - obtain if required for follow up after incident has been controlled.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='gender',
            field=models.CharField(blank=True, help_text='Reported gender of the patient, if known.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emergencypatient',
            name='name',
            field=models.CharField(blank=True, default='UNKNOWN', help_text='Name of the patient. Change this field once the name is known.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='Has_this_been_escalated',
            field=models.BooleanField(default=False, help_text='Select if this incident has been delegated to another authority, as specificed below:'),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='Has_this_been_resolved',
            field=models.BooleanField(default=False, help_text='Select if this incident has been resolved and no further action is required.'),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='emergency_action',
            field=models.TextField(help_text='Briefly explain what has been done to address the emergency situation. Provide as much detail as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='emergency_message_type',
            field=models.CharField(choices=[('C', 'Child Safety'), ('E', 'Environmental'), ('M', 'Medical'), ('O', 'Other'), ('S', 'Security')], default='M', help_text='Select the nature of the emergency incident.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='escalated_to',
            field=models.CharField(help_text='Specify a 000 department, company, custodian, etc.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='patient_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.emergencypatient'),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='recipient',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Message was received by this Operator.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='historicalemergencymessage',
            name='sender',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Message was sent by this Operator.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='age',
            field=models.IntegerField(blank=True, help_text='Approximate age of patient, if known.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='contact_email',
            field=models.CharField(blank=True, help_text='Obtain if required for follow up after incident has been controlled.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone is preferred - obtain if required for follow up after incident has been controlled.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='gender',
            field=models.CharField(blank=True, help_text='Reported gender of the patient, if known.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalemergencypatient',
            name='name',
            field=models.CharField(blank=True, default='UNKNOWN', help_text='Name of the patient. Change this field once the name is known.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='message_info',
            field=models.TextField(blank=True, help_text='Message details.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Message was received by this Operator.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='sender',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Message was sent by this Operator.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='base',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select the place the Operator is assigned to from the list.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.place'),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='name',
            field=models.CharField(help_text='Name of the Operator.', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaloperator',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Select the role of the Operator from the list.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.role'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='place',
            field=models.CharField(help_text='Location assigned for the event.', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalrole',
            name='title',
            field=models.CharField(help_text='Role assigned for the event', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_info',
            field=models.TextField(blank=True, help_text='Message details.', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Message was received by this Operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_recipient', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='Message was sent by this Operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_sender', to='float.operator'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='base',
            field=models.ForeignKey(blank=True, help_text='Select the place the Operator is assigned to from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_base', to='float.place'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(help_text='Name of the Operator.', max_length=50),
        ),
        migrations.AlterField(
            model_name='operator',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Select the role of the Operator from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_role', to='float.role'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(help_text='Location assigned for the event.', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(help_text='Role assigned for the event', max_length=50),
        ),
    ]
