# Generated by Django 4.1.3 on 2022-12-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0008_historicalincident_historicalincidentmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincidentmessage',
            name='incident_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.incident'),
        ),
        migrations.AddField(
            model_name='historicalincidentpatient',
            name='incident_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.incident'),
        ),
        migrations.AddField(
            model_name='incidentmessage',
            name='incident_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_incidentmessage_ref', to='float.incident'),
        ),
        migrations.AddField(
            model_name='incidentpatient',
            name='incident_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_incident_ref', to='float.incident'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='patient_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_incidentpatient_ref', to='float.incidentpatient'),
        ),
    ]
