# Generated by Django 4.1.3 on 2022-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0009_historicalincidentmessage_incident_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincidentmessage',
            name='reported_location',
            field=models.CharField(blank=True, help_text="Sender Operator's reported location, if provided - recipient location should be recorded if needed as message info.", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='incidentmessage',
            name='reported_location',
            field=models.CharField(blank=True, help_text="Sender Operator's reported location, if provided - recipient location should be recorded if needed as message info.", max_length=256, null=True),
        ),
    ]
