# Generated by Django 4.1.3 on 2022-12-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0011_rename_incident_action_historicalincident_action_taken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalincident',
            old_name='Has_this_been_escalated',
            new_name='has_this_been_escalated',
        ),
        migrations.RenameField(
            model_name='historicalincident',
            old_name='Has_this_been_controlled',
            new_name='is_incident_controlled',
        ),
        migrations.RenameField(
            model_name='historicalincident',
            old_name='Has_this_been_resolved',
            new_name='is_incident_resolved',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='Has_this_been_escalated',
            new_name='has_this_been_escalated',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='Has_this_been_controlled',
            new_name='is_incident_controlled',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='Has_this_been_resolved',
            new_name='is_incident_resolved',
        ),
    ]
