# Generated by Django 4.1.3 on 2022-12-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0012_rename_has_this_been_escalated_historicalincident_has_this_been_escalated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentmessage',
            name='incident_ref',
        ),
        migrations.RemoveField(
            model_name='incidentmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='incidentmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='historicalmessage',
            name='incident_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.incident'),
        ),
        migrations.AddField(
            model_name='message',
            name='incident_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new patient or select an existing patient to allocate a Patient ID (even if details of patient are not known at the time of the message)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_incidentmessage_ref', to='float.incident'),
        ),
        migrations.DeleteModel(
            name='HistoricalIncidentMessage',
        ),
        migrations.DeleteModel(
            name='IncidentMessage',
        ),
    ]
