# Generated by Django 4.1.3 on 2022-12-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0013_remove_incidentmessage_incident_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessage',
            name='incident_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Create a new incident or select an existing incident.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.incident'),
        ),
        migrations.AlterField(
            model_name='message',
            name='incident_ref',
            field=models.ForeignKey(blank=True, help_text='Create a new incident or select an existing incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_incidentmessage_ref', to='float.incident'),
        ),
    ]
