# Generated by Django 4.1.3 on 2022-12-03 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('float', '0014_alter_historicalmessage_incident_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='last_updated_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='last_updated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='incident_message_type',
            field=models.CharField(choices=[('C', 'Child Safety - missing, endangered, threatened, etc'), ('E', 'Environmental - location or structure based issues.'), ('M', 'Medical - injuries and illness of people involved in the event.'), ('O', 'Operational - preventing the effective execution of the event.'), ('S', 'Security - threats to people involved in the event.'), ('U', 'Undefined threats to the event.')], default='M', help_text='Select the nature of the incident.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_message_type',
            field=models.CharField(choices=[('C', 'Child Safety - missing, endangered, threatened, etc'), ('E', 'Environmental - location or structure based issues.'), ('M', 'Medical - injuries and illness of people involved in the event.'), ('O', 'Operational - preventing the effective execution of the event.'), ('S', 'Security - threats to people involved in the event.'), ('U', 'Undefined threats to the event.')], default='M', help_text='Select the nature of the incident.', max_length=1, null=True),
        ),
    ]
