# Generated by Django 4.1.3 on 2022-12-03 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('float', '0001_squashed_0015_historicalmessage_last_updated_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='base',
            field=models.ForeignKey(blank=True, help_text='Select the place the Operator is assigned to from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_operator_base', to='float.place'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Select the role of the Operator from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_operator_role', to='float.role'),
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_updated_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text='Name of the Security detail.', max_length=50)),
                ('callsign', models.CharField(help_text='Callsign of the Security detail.', max_length=50)),
                ('base', models.ForeignKey(blank=True, help_text='Select the place the Security detail is assigned to from the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_security_base', to='float.place')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSecurity',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Name of the Security detail.', max_length=50)),
                ('callsign', models.CharField(help_text='Callsign of the Security detail.', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('base', models.ForeignKey(blank=True, db_constraint=False, help_text='Select the place the Security detail is assigned to from the list.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='float.place')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical security',
                'verbose_name_plural': 'historical securitys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
