# Generated by Django 4.1.3 on 2022-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0016_alter_operator_base_alter_operator_role_security_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('command_weighting', 'name')},
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='historicaloperator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
