# Generated by Django 4.1.3 on 2022-12-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0018_alter_security_options_historicaloperator_callsign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='base',
        ),
        migrations.DeleteModel(
            name='HistoricalSecurity',
        ),
        migrations.DeleteModel(
            name='Security',
        ),
    ]
