# Generated by Django 6.0.4 on 2026-05-03 05:44

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0019_remove_security_base_delete_historicalsecurity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Application Instance/Server ID', max_length=50)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('address', models.CharField(blank=True, help_text='Address/URL of cloud instance', max_length=256, null=True)),
                ('sync', models.BooleanField(default=False, help_text='should we Sych with this upstream?')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event/Activity name', max_length=50)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'ordering': ('command_weighting', 'base', 'name')},
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Briefly explain what has been done to address the incident situation. Provide as much detail as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='cause_of_injury',
            field=models.TextField(blank=True, help_text='What was the cause of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='effects_of_injury',
            field=models.TextField(blank=True, help_text='What are the signs/symptoms of the injury, other observations?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='escalated_to',
            field=models.CharField(blank=True, help_text='Specify a 000 department, company, custodian, etc.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='nature_of_injury',
            field=models.TextField(blank=True, help_text='What is the nature of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='treatment_provided',
            field=models.TextField(blank=True, help_text='What treatment has been provided to the injury at this', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmessage',
            name='message_entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Briefly explain what has been done to address the incident situation. Provide as much detail as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cause_of_injury',
            field=models.TextField(blank=True, help_text='What was the cause of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='effects_of_injury',
            field=models.TextField(blank=True, help_text='What are the signs/symptoms of the injury, other observations?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='escalated_to',
            field=models.CharField(blank=True, help_text='Specify a 000 department, company, custodian, etc.', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='nature_of_injury',
            field=models.TextField(blank=True, help_text='What is the nature of the injury?', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='treatment_provided',
            field=models.TextField(blank=True, help_text='What treatment has been provided to the injury at this', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_entry_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalApplicationInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Application Instance/Server ID', max_length=50)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('address', models.CharField(blank=True, help_text='Address/URL of cloud instance', max_length=256, null=True)),
                ('sync', models.BooleanField(default=False, help_text='should we Sych with this upstream?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical application instance',
                'verbose_name_plural': 'historical application instances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Event/Activity name', max_length=50)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
