# Generated by Django 6.0.4 on 2026-05-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('float', '0020_applicationinstance_event_alter_operator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationinstance',
            name='me',
            field=models.BooleanField(default=False, help_text='Is this us?'),
        ),
        migrations.AddField(
            model_name='historicalapplicationinstance',
            name='me',
            field=models.BooleanField(default=False, help_text='Is this us?'),
        ),
        migrations.AlterField(
            model_name='applicationinstance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalapplicationinstance',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
